#!/bin/bash

usage="usage: <$0> <username> <key>" 
username=$1
key=$2

if [ -z "$username" ] || [ -z "$key" ] 
then
	echo "Script error: $usage"
	exit 1
elif [ "$EUID" -ne 0 ]
then
	echo "Script error: this script needs to be run with root priviledges."
	exit 1
fi

adduser "$username"
mkdir  /home/"$username"/.ssh
chmod 0777  /home/"$username"/.ssh
touch /home/"$username"/.ssh/authorized_keys
chmod 0777 /home/"$username"/.ssh/authorized_keys

userid="$(grep "$username" /etc/passwd | awk -F: '{print $3}')"
groupid="$(grep "$username" /etc/passwd | awk -F: '{print $4}')"

echo "$key" > /home/"$username"/.ssh/authorized_keys
chown -R "$userid":"$groupid" /home/"$username"/.ssh
chmod 0600 /home/"$username"/.ssh/authorized_keys
chmod 0700 /home/"$username"/.ssh

service ssh restart